-- PostgreSQL varianta ../mysql/20261002000002.sql (stejné schéma). Trigger updateDate používá funkci
-- firecms_set_update_date() z migrace jádra (structures), na které skupina pluginu závisí.
DROP TABLE IF EXISTS "firecms_plugin_statistics";
CREATE TABLE "firecms_plugin_statistics" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"session" varchar(32) NOT NULL,
	"ip" text NOT NULL,
	"agent" text NOT NULL,
	PRIMARY KEY ("id")
);
CREATE TRIGGER "firecms_plugin_statistics_updateDate" BEFORE UPDATE ON "firecms_plugin_statistics" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();
