-- PostgreSQL varianta ../mysql/20261002000001.sql (stejné schéma). Trigger updateDate používá funkci
-- firecms_set_update_date() z migrace jádra (structures), na které skupina pluginu závisí.
DROP TABLE IF EXISTS "firecms_plugin_stalkers";
CREATE TABLE "firecms_plugin_stalkers" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"createdBy" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"ip" text NOT NULL,
	"url" text NOT NULL,
	"data" text,
	PRIMARY KEY ("id")
);
CREATE INDEX "firecms_plugin_stalkers_createdBy" ON "firecms_plugin_stalkers" ("createdBy");
CREATE TRIGGER "firecms_plugin_stalkers_updateDate" BEFORE UPDATE ON "firecms_plugin_stalkers" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

ALTER TABLE "firecms_plugin_stalkers" ADD CONSTRAINT "stalkers_ibfk_1" FOREIGN KEY ("createdBy") REFERENCES "firecms_users" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
