-- PostgreSQL varianta data/migrations/structures/20261001000000.sql (stejné schéma jádra).
-- Identifikátory jsou v uvozovkách (camelCase), příznaky boolean, enumy varchar + CHECK,
-- updateDate přes trigger, cizí klíče DEFERRABLE (datové migrace je odkládají, viz SET CONSTRAINTS).

-- updateDate jako v MariaDB (ON UPDATE current_timestamp()): nastaví se při skutečné změně řádku,
-- pokud ho UPDATE sám nezměnil
CREATE OR REPLACE FUNCTION "firecms_set_update_date"() RETURNS trigger AS $$
BEGIN
	IF NEW IS DISTINCT FROM OLD AND NEW."updateDate" IS NOT DISTINCT FROM OLD."updateDate" THEN
		NEW."updateDate" := LOCALTIMESTAMP(0);
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE "firecms_roles" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"parentId" integer,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"default" boolean NOT NULL DEFAULT false,
	"position" smallint NOT NULL,
	"name" varchar(50) NOT NULL,
	"title" varchar(50) NOT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "firecms_roles_name" UNIQUE ("name")
);
CREATE INDEX "firecms_roles_parentId" ON "firecms_roles" ("parentId");
CREATE TRIGGER "firecms_roles_updateDate" BEFORE UPDATE ON "firecms_roles" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_users" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"roleId" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"username" varchar(60) NOT NULL,
	"password" varchar(60) NOT NULL,
	"email" varchar(100) NOT NULL,
	"active" boolean NOT NULL,
	"nickname" varchar(50),
	"firstName" varchar(50) NOT NULL,
	"surname" varchar(50) NOT NULL,
	"recoveryPasswordTime" timestamp(0),
	"recoveryPasswordToken" varchar(24),
	"oauthService" varchar(20),
	"oauthId" varchar(20),
	PRIMARY KEY ("id"),
	CONSTRAINT "firecms_users_loginKey" UNIQUE ("username"),
	CONSTRAINT "firecms_users_email" UNIQUE ("email")
);
CREATE INDEX "firecms_users_nicknameKey" ON "firecms_users" ("nickname");
CREATE INDEX "firecms_users_roleId" ON "firecms_users" ("roleId");
CREATE TRIGGER "firecms_users_updateDate" BEFORE UPDATE ON "firecms_users" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_languages" (
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"active" boolean NOT NULL DEFAULT true,
	"default" boolean NOT NULL DEFAULT false,
	"position" integer NOT NULL,
	"name" varchar(20) NOT NULL,
	"shortcut" varchar(2) NOT NULL,
	PRIMARY KEY ("languageId")
);
CREATE INDEX "firecms_languages_activeDefault" ON "firecms_languages" ("active", "default");
CREATE TRIGGER "firecms_languages_updateDate" BEFORE UPDATE ON "firecms_languages" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_comments" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"parentId" integer,
	"languageId" char(2) NOT NULL,
	"createdBy" integer,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"left" integer NOT NULL,
	"right" integer NOT NULL,
	"status" varchar(7) NOT NULL CHECK ("status" IN ('publish', 'pending', 'trash')),
	"author" varchar(100),
	"authorEmail" varchar(100),
	"title" varchar(150) NOT NULL,
	"text" text NOT NULL,
	"userIp" text NOT NULL,
	"userAgent" text NOT NULL,
	PRIMARY KEY ("id")
);
CREATE INDEX "firecms_comments_createdBy" ON "firecms_comments" ("createdBy");
CREATE INDEX "firecms_comments_parentId" ON "firecms_comments" ("parentId");
CREATE INDEX "firecms_comments_languageId" ON "firecms_comments" ("languageId");
CREATE TRIGGER "firecms_comments_updateDate" BEFORE UPDATE ON "firecms_comments" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_sections" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"active" boolean NOT NULL DEFAULT true,
	"position" integer NOT NULL DEFAULT 0,
	PRIMARY KEY ("id")
);
CREATE TRIGGER "firecms_sections_updateDate" BEFORE UPDATE ON "firecms_sections" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_sectionDescriptions" (
	"sectionId" integer NOT NULL,
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"title" varchar(255),
	"content" text,
	"seoTitle" text,
	"seoDescription" text,
	"seoKeywords" text,
	PRIMARY KEY ("sectionId", "languageId")
);
CREATE INDEX "firecms_sectionDescriptions_languageId" ON "firecms_sectionDescriptions" ("languageId");
CREATE TRIGGER "firecms_sectionDescriptions_updateDate" BEFORE UPDATE ON "firecms_sectionDescriptions" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_settings" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"imageResolution" varchar(20) NOT NULL,
	"themePath" varchar(100),
	"contactPhone" varchar(50),
	"mapLatitude" numeric(9,6),
	"mapLongitude" numeric(9,6),
	PRIMARY KEY ("id")
);
CREATE TRIGGER "firecms_settings_updateDate" BEFORE UPDATE ON "firecms_settings" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_settingDescriptions" (
	"settingId" integer NOT NULL,
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"mainTitle" varchar(255),
	"mainDescription" text,
	"mainEmail" varchar(100),
	"contactAddress" text,
	"seoTitle" text,
	"seoDescription" text,
	"seoKeywords" text,
	PRIMARY KEY ("settingId", "languageId")
);
CREATE INDEX "firecms_settingDescriptions_languageId" ON "firecms_settingDescriptions" ("languageId");
CREATE TRIGGER "firecms_settingDescriptions_updateDate" BEFORE UPDATE ON "firecms_settingDescriptions" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_articles" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"sectionId" integer NOT NULL,
	"historyId" integer,
	"createdBy" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"publishingDate" timestamp(0) NOT NULL,
	"expiringDate" timestamp(0),
	"active" boolean NOT NULL DEFAULT true,
	"status" varchar(10) NOT NULL DEFAULT 'draft' CHECK ("status" IN ('publish', 'pending', 'draft', 'auto-draft', 'trash')),
	"public" boolean NOT NULL DEFAULT true,
	PRIMARY KEY ("id")
);
CREATE INDEX "firecms_articles_historyId" ON "firecms_articles" ("historyId");
CREATE INDEX "firecms_articles_createdBy" ON "firecms_articles" ("createdBy");
CREATE INDEX "firecms_articles_sectionId" ON "firecms_articles" ("sectionId");
CREATE TRIGGER "firecms_articles_updateDate" BEFORE UPDATE ON "firecms_articles" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_categories" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"sectionId" integer NOT NULL,
	"parentId" integer,
	"historyId" integer,
	"createdBy" integer NOT NULL DEFAULT 1,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"publishingDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"expiringDate" timestamp(0),
	"active" boolean NOT NULL DEFAULT true,
	"status" varchar(10) NOT NULL DEFAULT 'draft' CHECK ("status" IN ('publish', 'pending', 'draft', 'auto-draft', 'trash')),
	"position" integer,
	"level" integer NOT NULL DEFAULT 0,
	"categoryLeft" integer,
	"categoryRight" integer,
	"showInMenu" boolean NOT NULL DEFAULT true,
	"public" boolean NOT NULL DEFAULT true,
	PRIMARY KEY ("id")
);
CREATE INDEX "firecms_categories_fkParentId" ON "firecms_categories" ("parentId");
CREATE INDEX "firecms_categories_categoryLeftCategoryRight" ON "firecms_categories" ("categoryLeft", "categoryRight");
CREATE INDEX "firecms_categories_activeYnParentIdPosition" ON "firecms_categories" ("active", "parentId", "position");
CREATE INDEX "firecms_categories_createdBy" ON "firecms_categories" ("createdBy");
CREATE INDEX "firecms_categories_historyId" ON "firecms_categories" ("historyId");
CREATE INDEX "firecms_categories_sectionId" ON "firecms_categories" ("sectionId");
CREATE TRIGGER "firecms_categories_updateDate" BEFORE UPDATE ON "firecms_categories" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_articleComments" (
	"articleId" integer NOT NULL,
	"commentId" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0)
);
CREATE INDEX "firecms_articleComments_articleId" ON "firecms_articleComments" ("articleId");
CREATE INDEX "firecms_articleComments_commentId" ON "firecms_articleComments" ("commentId");
CREATE TRIGGER "firecms_articleComments_updateDate" BEFORE UPDATE ON "firecms_articleComments" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_articleDescriptions" (
	"articleId" integer NOT NULL,
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"title" varchar(512),
	"excerpt" text,
	"content" text,
	"seoTitle" text,
	"seoDescription" text,
	"seoKeywords" text,
	"viewCount" integer NOT NULL DEFAULT 0,
	PRIMARY KEY ("articleId", "languageId")
);
CREATE INDEX "firecms_articleDescriptions_languageId" ON "firecms_articleDescriptions" ("languageId");
CREATE INDEX "firecms_articleDescriptions_articleId" ON "firecms_articleDescriptions" ("articleId");
CREATE TRIGGER "firecms_articleDescriptions_updateDate" BEFORE UPDATE ON "firecms_articleDescriptions" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_fileFolders" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"parentId" integer,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"name" varchar(200) NOT NULL,
	"default" boolean NOT NULL DEFAULT false,
	"position" integer NOT NULL,
	"level" integer NOT NULL DEFAULT 0,
	PRIMARY KEY ("id")
);
CREATE INDEX "firecms_fileFolders_parentId" ON "firecms_fileFolders" ("parentId");
CREATE TRIGGER "firecms_fileFolders_updateDate" BEFORE UPDATE ON "firecms_fileFolders" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_files" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"fileFolderId" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"originalName" varchar(100) NOT NULL,
	"newName" varchar(100) NOT NULL DEFAULT '',
	"diskName" varchar(50) NOT NULL,
	"extension" varchar(5) NOT NULL,
	"mimeType" varchar(20) NOT NULL,
	"size" integer NOT NULL,
	"isImage" boolean NOT NULL,
	"viewCount" integer NOT NULL DEFAULT 0,
	PRIMARY KEY ("id")
);
CREATE INDEX "firecms_files_fileFolderId" ON "firecms_files" ("fileFolderId");
CREATE TRIGGER "firecms_files_updateDate" BEFORE UPDATE ON "firecms_files" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_articleFiles" (
	"articleId" integer NOT NULL,
	"fileId" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"isMain" boolean NOT NULL,
	"position" smallint NOT NULL,
	PRIMARY KEY ("articleId", "fileId")
);
CREATE INDEX "firecms_articleFiles_fileId" ON "firecms_articleFiles" ("fileId");
CREATE INDEX "firecms_articleFiles_articleId" ON "firecms_articleFiles" ("articleId");
CREATE TRIGGER "firecms_articleFiles_updateDate" BEFORE UPDATE ON "firecms_articleFiles" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_metas" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"languageId" char(2),
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"type" varchar(20) NOT NULL,
	"isManual" boolean NOT NULL DEFAULT true,
	"key" varchar(200) NOT NULL,
	"value" text NOT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "firecms_metas_languageIdTypeKey" UNIQUE ("languageId", "type", "key")
);
CREATE TRIGGER "firecms_metas_updateDate" BEFORE UPDATE ON "firecms_metas" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_tags" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	PRIMARY KEY ("id")
);
CREATE TRIGGER "firecms_tags_updateDate" BEFORE UPDATE ON "firecms_tags" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_tagDescriptions" (
	"tagId" integer NOT NULL,
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"name" varchar(100) NOT NULL,
	PRIMARY KEY ("tagId", "languageId", "name")
);
CREATE INDEX "firecms_tagDescriptions_languageId" ON "firecms_tagDescriptions" ("languageId");
CREATE INDEX "firecms_tagDescriptions_tagId" ON "firecms_tagDescriptions" ("tagId");
CREATE TRIGGER "firecms_tagDescriptions_updateDate" BEFORE UPDATE ON "firecms_tagDescriptions" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_articleMetas" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"articleId" integer NOT NULL,
	"metaId" integer NOT NULL,
	"createdBy" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"value" text NOT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "firecms_articleMetas_articleIdMetaId" UNIQUE ("articleId", "metaId")
);
CREATE INDEX "firecms_articleMetas_createdBy" ON "firecms_articleMetas" ("createdBy");
CREATE INDEX "firecms_articleMetas_metaId" ON "firecms_articleMetas" ("metaId");
CREATE TRIGGER "firecms_articleMetas_updateDate" BEFORE UPDATE ON "firecms_articleMetas" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_articleTags" (
	"articleId" integer NOT NULL,
	"tagId" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	PRIMARY KEY ("articleId", "tagId")
);
CREATE INDEX "firecms_articleTags_tagId" ON "firecms_articleTags" ("tagId");
CREATE INDEX "firecms_articleTags_articleId" ON "firecms_articleTags" ("articleId");
CREATE TRIGGER "firecms_articleTags_updateDate" BEFORE UPDATE ON "firecms_articleTags" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_categoryArticle" (
	"categoryId" integer NOT NULL,
	"articleId" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"isMain" boolean NOT NULL,
	PRIMARY KEY ("categoryId", "articleId")
);
CREATE INDEX "firecms_categoryArticle_categoryId" ON "firecms_categoryArticle" ("categoryId");
CREATE INDEX "firecms_categoryArticle_articleId" ON "firecms_categoryArticle" ("articleId");
CREATE TRIGGER "firecms_categoryArticle_updateDate" BEFORE UPDATE ON "firecms_categoryArticle" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_categoryComments" (
	"categoryId" integer NOT NULL,
	"commentId" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0)
);
CREATE INDEX "firecms_categoryComments_categoryId" ON "firecms_categoryComments" ("categoryId");
CREATE INDEX "firecms_categoryComments_commentId" ON "firecms_categoryComments" ("commentId");
CREATE TRIGGER "firecms_categoryComments_updateDate" BEFORE UPDATE ON "firecms_categoryComments" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_categoryDescriptions" (
	"categoryId" integer NOT NULL,
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"title" varchar(512),
	"excerpt" text,
	"content" text,
	"seoTitle" text,
	"seoDescription" text,
	"seoKeywords" text,
	"viewCount" integer NOT NULL DEFAULT 0,
	PRIMARY KEY ("categoryId", "languageId")
);
CREATE INDEX "firecms_categoryDescriptions_relCategoryCategoryDescription" ON "firecms_categoryDescriptions" ("categoryId");
CREATE INDEX "firecms_categoryDescriptions_languageId" ON "firecms_categoryDescriptions" ("languageId");
CREATE TRIGGER "firecms_categoryDescriptions_updateDate" BEFORE UPDATE ON "firecms_categoryDescriptions" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_categoryFiles" (
	"categoryId" integer NOT NULL,
	"fileId" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"isMain" boolean NOT NULL,
	"position" smallint NOT NULL,
	PRIMARY KEY ("categoryId", "fileId")
);
CREATE INDEX "firecms_categoryFiles_categoryId" ON "firecms_categoryFiles" ("categoryId");
CREATE INDEX "firecms_categoryFiles_fileId" ON "firecms_categoryFiles" ("fileId");
CREATE TRIGGER "firecms_categoryFiles_updateDate" BEFORE UPDATE ON "firecms_categoryFiles" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_categoryMetas" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"categoryId" integer NOT NULL,
	"metaId" integer NOT NULL,
	"createdBy" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"value" text NOT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "firecms_categoryMetas_categoryIdMetaId" UNIQUE ("categoryId", "metaId")
);
CREATE INDEX "firecms_categoryMetas_createdBy" ON "firecms_categoryMetas" ("createdBy");
CREATE INDEX "firecms_categoryMetas_metaId" ON "firecms_categoryMetas" ("metaId");
CREATE TRIGGER "firecms_categoryMetas_updateDate" BEFORE UPDATE ON "firecms_categoryMetas" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_categoryTags" (
	"categoryId" integer NOT NULL,
	"tagId" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0)
);
CREATE INDEX "firecms_categoryTags_categoryId" ON "firecms_categoryTags" ("categoryId");
CREATE INDEX "firecms_categoryTags_tagId" ON "firecms_categoryTags" ("tagId");
CREATE TRIGGER "firecms_categoryTags_updateDate" BEFORE UPDATE ON "firecms_categoryTags" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_cronTasks" (
	"name" varchar(100) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"lastRunAt" timestamp(0),
	"lastFinishedAt" timestamp(0),
	"lastStatus" varchar(5) CHECK ("lastStatus" IN ('ok', 'error')),
	"lastMessage" varchar(1000),
	"lastDuration" numeric(10,3),
	PRIMARY KEY ("name")
);
CREATE TRIGGER "firecms_cronTasks_updateDate" BEFORE UPDATE ON "firecms_cronTasks" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_domains" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"domain" varchar(255) NOT NULL,
	"active" boolean NOT NULL DEFAULT true,
	"default" boolean NOT NULL DEFAULT true,
	"position" integer NOT NULL DEFAULT 0,
	PRIMARY KEY ("id"),
	CONSTRAINT "firecms_domains_domain" UNIQUE ("domain")
);
CREATE INDEX "firecms_domains_languageId" ON "firecms_domains" ("languageId");
CREATE TRIGGER "firecms_domains_updateDate" BEFORE UPDATE ON "firecms_domains" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_dynamicForms" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"itemsSpecifications" text NOT NULL,
	"templateName" varchar(50) NOT NULL,
	"whereToSend" varchar(20),
	"afterSendInformations" varchar(200),
	"createdBy" integer NOT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "firecms_dynamicForms_templateName" UNIQUE ("templateName")
);
CREATE TRIGGER "firecms_dynamicForms_updateDate" BEFORE UPDATE ON "firecms_dynamicForms" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_dynamicFormDescriptions" (
	"dynamicFormId" integer NOT NULL,
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"title" varchar(50) NOT NULL,
	"items" text NOT NULL,
	"submitMessage" varchar(200),
	PRIMARY KEY ("dynamicFormId", "languageId")
);
CREATE INDEX "firecms_dynamicFormDescriptions_languageId" ON "firecms_dynamicFormDescriptions" ("languageId");
CREATE TRIGGER "firecms_dynamicFormDescriptions_updateDate" BEFORE UPDATE ON "firecms_dynamicFormDescriptions" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_dynamicFormSendedValues" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"dynamicFormId" integer NOT NULL,
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"sendedValues" text NOT NULL,
	PRIMARY KEY ("id")
);
CREATE INDEX "firecms_dynamicFormSendedValues_dynamicFormId" ON "firecms_dynamicFormSendedValues" ("dynamicFormId");
CREATE INDEX "firecms_dynamicFormSendedValues_languageId" ON "firecms_dynamicFormSendedValues" ("languageId");
CREATE INDEX "firecms_dynamicFormSendedValues_dynamicFormIdLanguageId" ON "firecms_dynamicFormSendedValues" ("dynamicFormId", "languageId");
CREATE TRIGGER "firecms_dynamicFormSendedValues_updateDate" BEFORE UPDATE ON "firecms_dynamicFormSendedValues" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_menus" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"active" boolean NOT NULL DEFAULT true,
	"location" varchar(256) NOT NULL,
	"createdBy" integer,
	PRIMARY KEY ("id")
);
CREATE TRIGGER "firecms_menus_updateDate" BEFORE UPDATE ON "firecms_menus" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_menuDescriptions" (
	"menuId" integer NOT NULL,
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"title" varchar(255),
	PRIMARY KEY ("menuId", "languageId")
);
CREATE INDEX "firecms_menuDescriptions_languageId" ON "firecms_menuDescriptions" ("languageId");
CREATE TRIGGER "firecms_menuDescriptions_updateDate" BEFORE UPDATE ON "firecms_menuDescriptions" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_menuItems" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"menuId" integer NOT NULL,
	"parentId" integer,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"active" boolean NOT NULL DEFAULT true,
	"position" integer NOT NULL DEFAULT 0,
	"linkType" varchar(8) NOT NULL CHECK ("linkType" IN ('category', 'article', 'page', 'section', 'url', 'route')),
	"target" varchar(512) NOT NULL,
	"newWindow" boolean NOT NULL DEFAULT false,
	PRIMARY KEY ("id")
);
CREATE INDEX "firecms_menuItems_menuId" ON "firecms_menuItems" ("menuId");
CREATE INDEX "firecms_menuItems_parentId" ON "firecms_menuItems" ("parentId");
CREATE INDEX "firecms_menuItems_linkTypeTarget" ON "firecms_menuItems" ("linkType", "target");
CREATE TRIGGER "firecms_menuItems_updateDate" BEFORE UPDATE ON "firecms_menuItems" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_menuItemDescriptions" (
	"menuItemId" integer NOT NULL,
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"label" varchar(255),
	PRIMARY KEY ("menuItemId", "languageId")
);
CREATE INDEX "firecms_menuItemDescriptions_languageId" ON "firecms_menuItemDescriptions" ("languageId");
CREATE TRIGGER "firecms_menuItemDescriptions_updateDate" BEFORE UPDATE ON "firecms_menuItemDescriptions" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_menuItemFiles" (
	"menuItemId" integer NOT NULL,
	"fileId" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"position" integer NOT NULL DEFAULT 0,
	PRIMARY KEY ("menuItemId", "fileId")
);
CREATE INDEX "firecms_menuItemFiles_fileId" ON "firecms_menuItemFiles" ("fileId");
CREATE TRIGGER "firecms_menuItemFiles_updateDate" BEFORE UPDATE ON "firecms_menuItemFiles" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_modules" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"parentId" integer,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"name" varchar(50),
	"privilege" varchar(50),
	"title" varchar(50) NOT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "firecms_modules_name" UNIQUE ("name")
);
CREATE INDEX "firecms_modules_parentId" ON "firecms_modules" ("parentId");
CREATE INDEX "firecms_modules_namePrivilege" ON "firecms_modules" ("name", "privilege");
CREATE TRIGGER "firecms_modules_updateDate" BEFORE UPDATE ON "firecms_modules" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_pages" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"parentId" integer,
	"createdBy" integer,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"active" boolean NOT NULL DEFAULT true,
	"status" varchar(7) NOT NULL DEFAULT 'draft' CHECK ("status" IN ('publish', 'draft')),
	"public" boolean NOT NULL DEFAULT true,
	"position" integer NOT NULL DEFAULT 0,
	"template" varchar(50),
	PRIMARY KEY ("id")
);
CREATE INDEX "firecms_pages_createdBy" ON "firecms_pages" ("createdBy");
CREATE INDEX "firecms_pages_parentId" ON "firecms_pages" ("parentId");
CREATE TRIGGER "firecms_pages_updateDate" BEFORE UPDATE ON "firecms_pages" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_pageDescriptions" (
	"pageId" integer NOT NULL,
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"title" varchar(512),
	"content" text,
	"seoTitle" text,
	"seoDescription" text,
	"seoKeywords" text,
	PRIMARY KEY ("pageId", "languageId")
);
CREATE INDEX "firecms_pageDescriptions_languageId" ON "firecms_pageDescriptions" ("languageId");
CREATE TRIGGER "firecms_pageDescriptions_updateDate" BEFORE UPDATE ON "firecms_pageDescriptions" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_pageFiles" (
	"pageId" integer NOT NULL,
	"fileId" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"position" integer NOT NULL DEFAULT 0,
	PRIMARY KEY ("pageId", "fileId")
);
CREATE INDEX "firecms_pageFiles_fileId" ON "firecms_pageFiles" ("fileId");
CREATE TRIGGER "firecms_pageFiles_updateDate" BEFORE UPDATE ON "firecms_pageFiles" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_roleModule" (
	"roleId" integer NOT NULL,
	"moduleId" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"privilege" varchar(15) NOT NULL,
	PRIMARY KEY ("roleId", "moduleId")
);
CREATE INDEX "firecms_roleModule_moduleId" ON "firecms_roleModule" ("moduleId");
CREATE TRIGGER "firecms_roleModule_updateDate" BEFORE UPDATE ON "firecms_roleModule" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_sliders" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"name" varchar(100) NOT NULL,
	"location" varchar(100) NOT NULL,
	"duration" integer NOT NULL,
	"speed" integer NOT NULL,
	"navigation" boolean NOT NULL,
	"manual" boolean NOT NULL,
	PRIMARY KEY ("id")
);
CREATE TRIGGER "firecms_sliders_updateDate" BEFORE UPDATE ON "firecms_sliders" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_sliderItems" (
	"sliderId" integer NOT NULL,
	"languageId" char(2) NOT NULL,
	"fileId" integer NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"position" smallint NOT NULL,
	"url" varchar(256) NOT NULL DEFAULT '',
	"text" varchar(256) NOT NULL DEFAULT '',
	PRIMARY KEY ("sliderId", "languageId", "position")
);
CREATE INDEX "firecms_sliderItems_languageId" ON "firecms_sliderItems" ("languageId");
CREATE INDEX "firecms_sliderItems_fileId" ON "firecms_sliderItems" ("fileId");
CREATE INDEX "firecms_sliderItems_sliderId" ON "firecms_sliderItems" ("sliderId");
CREATE TRIGGER "firecms_sliderItems_updateDate" BEFORE UPDATE ON "firecms_sliderItems" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_urlRedirections" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"oldUrl" varchar(2000) NOT NULL,
	"newUrl" varchar(2000) NOT NULL,
	"lastUsageDate" timestamp(0),
	PRIMARY KEY ("id")
);
CREATE INDEX "firecms_urlRedirections_languageId" ON "firecms_urlRedirections" ("languageId");
CREATE TRIGGER "firecms_urlRedirections_updateDate" BEFORE UPDATE ON "firecms_urlRedirections" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

CREATE TABLE "firecms_urls" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"languageId" char(2) NOT NULL,
	"createDate" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"updateDate" timestamp(0),
	"type" varchar(128) NOT NULL,
	"key" integer NOT NULL,
	"url" varchar(2000) NOT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "firecms_urls_languageIdTypeKey" UNIQUE ("languageId", "type", "key")
);
CREATE TRIGGER "firecms_urls_updateDate" BEFORE UPDATE ON "firecms_urls" FOR EACH ROW EXECUTE FUNCTION "firecms_set_update_date"();

-- cizí klíče až po založení všech tabulek (dump je řazený abecedně, ne podle závislostí)
ALTER TABLE "firecms_roles" ADD CONSTRAINT "roles_ibfk_1" FOREIGN KEY ("parentId") REFERENCES "firecms_roles" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_users" ADD CONSTRAINT "users_ibfk_2" FOREIGN KEY ("roleId") REFERENCES "firecms_roles" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_comments" ADD CONSTRAINT "comments_ibfk_3" FOREIGN KEY ("createdBy") REFERENCES "firecms_users" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_comments" ADD CONSTRAINT "comments_ibfk_4" FOREIGN KEY ("parentId") REFERENCES "firecms_comments" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_comments" ADD CONSTRAINT "comments_ibfk_6" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_sectionDescriptions" ADD CONSTRAINT "sectionDescriptions_ibfk_1" FOREIGN KEY ("sectionId") REFERENCES "firecms_sections" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_sectionDescriptions" ADD CONSTRAINT "sectionDescriptions_ibfk_2" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_settingDescriptions" ADD CONSTRAINT "settingDescriptions_ibfk_1" FOREIGN KEY ("settingId") REFERENCES "firecms_settings" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_settingDescriptions" ADD CONSTRAINT "settingDescriptions_ibfk_2" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articles" ADD CONSTRAINT "articles_ibfk_1" FOREIGN KEY ("historyId") REFERENCES "firecms_articles" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articles" ADD CONSTRAINT "articles_ibfk_2" FOREIGN KEY ("createdBy") REFERENCES "firecms_users" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articles" ADD CONSTRAINT "articles_section_fk" FOREIGN KEY ("sectionId") REFERENCES "firecms_sections" ("id") ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categories" ADD CONSTRAINT "categories_ibfk_1" FOREIGN KEY ("parentId") REFERENCES "firecms_categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categories" ADD CONSTRAINT "categories_ibfk_2" FOREIGN KEY ("createdBy") REFERENCES "firecms_users" ("id") ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categories" ADD CONSTRAINT "categories_ibfk_3" FOREIGN KEY ("historyId") REFERENCES "firecms_categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categories" ADD CONSTRAINT "categories_section_fk" FOREIGN KEY ("sectionId") REFERENCES "firecms_sections" ("id") ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articleComments" ADD CONSTRAINT "articleComments_ibfk_3" FOREIGN KEY ("articleId") REFERENCES "firecms_articles" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articleComments" ADD CONSTRAINT "articleComments_ibfk_4" FOREIGN KEY ("commentId") REFERENCES "firecms_comments" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articleDescriptions" ADD CONSTRAINT "articleDescriptions_ibfk_1" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articleDescriptions" ADD CONSTRAINT "articleDescriptions_ibfk_2" FOREIGN KEY ("articleId") REFERENCES "firecms_articles" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_fileFolders" ADD CONSTRAINT "fileFolders_ibfk_2" FOREIGN KEY ("parentId") REFERENCES "firecms_fileFolders" ("id") ON DELETE SET NULL ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_files" ADD CONSTRAINT "files_ibfk_2" FOREIGN KEY ("fileFolderId") REFERENCES "firecms_fileFolders" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articleFiles" ADD CONSTRAINT "articleFiles_ibfk_1" FOREIGN KEY ("articleId") REFERENCES "firecms_articles" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articleFiles" ADD CONSTRAINT "articleFiles_ibfk_2" FOREIGN KEY ("fileId") REFERENCES "firecms_files" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_metas" ADD CONSTRAINT "metas_ibfk_2" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_tagDescriptions" ADD CONSTRAINT "tagDescriptions_ibfk_3" FOREIGN KEY ("tagId") REFERENCES "firecms_tags" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_tagDescriptions" ADD CONSTRAINT "tagDescriptions_ibfk_4" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articleMetas" ADD CONSTRAINT "articleMetas_ibfk_1" FOREIGN KEY ("articleId") REFERENCES "firecms_articles" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articleMetas" ADD CONSTRAINT "articleMetas_ibfk_3" FOREIGN KEY ("createdBy") REFERENCES "firecms_users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articleMetas" ADD CONSTRAINT "articleMetas_ibfk_5" FOREIGN KEY ("metaId") REFERENCES "firecms_metas" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articleTags" ADD CONSTRAINT "articleTags_ibfk_3" FOREIGN KEY ("articleId") REFERENCES "firecms_articles" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_articleTags" ADD CONSTRAINT "articleTags_ibfk_4" FOREIGN KEY ("tagId") REFERENCES "firecms_tags" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categoryArticle" ADD CONSTRAINT "categoryArticle_ibfk_3" FOREIGN KEY ("categoryId") REFERENCES "firecms_categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categoryArticle" ADD CONSTRAINT "categoryArticle_ibfk_4" FOREIGN KEY ("articleId") REFERENCES "firecms_articles" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categoryComments" ADD CONSTRAINT "categoryComments_ibfk_3" FOREIGN KEY ("categoryId") REFERENCES "firecms_categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categoryComments" ADD CONSTRAINT "categoryComments_ibfk_4" FOREIGN KEY ("commentId") REFERENCES "firecms_comments" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categoryDescriptions" ADD CONSTRAINT "categoryDescriptions_ibfk_2" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categoryDescriptions" ADD CONSTRAINT "categoryDescriptions_ibfk_3" FOREIGN KEY ("categoryId") REFERENCES "firecms_categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categoryFiles" ADD CONSTRAINT "categoryFiles_ibfk_3" FOREIGN KEY ("categoryId") REFERENCES "firecms_categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categoryFiles" ADD CONSTRAINT "categoryFiles_ibfk_4" FOREIGN KEY ("fileId") REFERENCES "firecms_files" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categoryMetas" ADD CONSTRAINT "categoryMetas_ibfk_1" FOREIGN KEY ("categoryId") REFERENCES "firecms_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categoryMetas" ADD CONSTRAINT "categoryMetas_ibfk_3" FOREIGN KEY ("createdBy") REFERENCES "firecms_users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categoryMetas" ADD CONSTRAINT "categoryMetas_ibfk_5" FOREIGN KEY ("metaId") REFERENCES "firecms_metas" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categoryTags" ADD CONSTRAINT "categoryTags_ibfk_3" FOREIGN KEY ("categoryId") REFERENCES "firecms_categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_categoryTags" ADD CONSTRAINT "categoryTags_ibfk_4" FOREIGN KEY ("tagId") REFERENCES "firecms_tags" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_domains" ADD CONSTRAINT "domains_ibfk_1" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_dynamicFormDescriptions" ADD CONSTRAINT "dynamicFormDescriptions_ibfk_3" FOREIGN KEY ("dynamicFormId") REFERENCES "firecms_dynamicForms" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_dynamicFormDescriptions" ADD CONSTRAINT "dynamicFormDescriptions_ibfk_4" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_dynamicFormSendedValues" ADD CONSTRAINT "dynamicFormSendedValues_ibfk_1" FOREIGN KEY ("dynamicFormId") REFERENCES "firecms_dynamicForms" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_dynamicFormSendedValues" ADD CONSTRAINT "dynamicFormSendedValues_ibfk_3" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_menuDescriptions" ADD CONSTRAINT "menuDescriptions_ibfk_1" FOREIGN KEY ("menuId") REFERENCES "firecms_menus" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_menuDescriptions" ADD CONSTRAINT "menuDescriptions_ibfk_2" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_menuItems" ADD CONSTRAINT "menuItems_ibfk_1" FOREIGN KEY ("menuId") REFERENCES "firecms_menus" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_menuItems" ADD CONSTRAINT "menuItems_ibfk_2" FOREIGN KEY ("parentId") REFERENCES "firecms_menuItems" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_menuItemDescriptions" ADD CONSTRAINT "menuItemDescriptions_ibfk_1" FOREIGN KEY ("menuItemId") REFERENCES "firecms_menuItems" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_menuItemDescriptions" ADD CONSTRAINT "menuItemDescriptions_ibfk_2" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_menuItemFiles" ADD CONSTRAINT "menuItemFiles_ibfk_1" FOREIGN KEY ("menuItemId") REFERENCES "firecms_menuItems" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_menuItemFiles" ADD CONSTRAINT "menuItemFiles_ibfk_2" FOREIGN KEY ("fileId") REFERENCES "firecms_files" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_modules" ADD CONSTRAINT "modules_ibfk_1" FOREIGN KEY ("parentId") REFERENCES "firecms_modules" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_pages" ADD CONSTRAINT "pages_ibfk_1" FOREIGN KEY ("createdBy") REFERENCES "firecms_users" ("id") ON DELETE SET NULL ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_pages" ADD CONSTRAINT "pages_ibfk_2" FOREIGN KEY ("parentId") REFERENCES "firecms_pages" ("id") ON DELETE SET NULL ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_pageDescriptions" ADD CONSTRAINT "pageDescriptions_ibfk_1" FOREIGN KEY ("pageId") REFERENCES "firecms_pages" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_pageDescriptions" ADD CONSTRAINT "pageDescriptions_ibfk_2" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_pageFiles" ADD CONSTRAINT "pageFiles_ibfk_1" FOREIGN KEY ("pageId") REFERENCES "firecms_pages" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_pageFiles" ADD CONSTRAINT "pageFiles_ibfk_2" FOREIGN KEY ("fileId") REFERENCES "firecms_files" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_roleModule" ADD CONSTRAINT "roleModule_ibfk_6" FOREIGN KEY ("moduleId") REFERENCES "firecms_modules" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_roleModule" ADD CONSTRAINT "roleModule_ibfk_7" FOREIGN KEY ("roleId") REFERENCES "firecms_roles" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_sliderItems" ADD CONSTRAINT "sliderItems_ibfk_2" FOREIGN KEY ("sliderId") REFERENCES "firecms_sliders" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_sliderItems" ADD CONSTRAINT "sliderItems_ibfk_5" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_sliderItems" ADD CONSTRAINT "sliderItems_ibfk_6" FOREIGN KEY ("fileId") REFERENCES "firecms_files" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_urlRedirections" ADD CONSTRAINT "urlRedirections_ibfk_2" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "firecms_urls" ADD CONSTRAINT "urls_ibfk_2" FOREIGN KEY ("languageId") REFERENCES "firecms_languages" ("languageId") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
